language: java
sudo: false
jdk:
  - oraclejdk13
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: $SECURE_KEY
  app: $APP
  skip_cleanup: true