language: java
sudo: false
jdk:
  - oraclejdk13
before_install:
  - chmod +x mvnw
  - export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    - secure: 463935f8-4afe-457b-bce3-efd426b0f598
  app: $APP